# Site settings
name: ZT blog
email: ztmail723@gmail.com
author: 正锑
url: http://ztmagic.club/
resume_site: http://ztmagic.club/
github: https://github.com/ztmail723
baseurl: ''
description: Actually, less is more!
meta_description: 正锑;个人博客
motto: 杜绝戾气
banner: 杜绝戾气

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ztmail723

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

