# Site settings
name: ZT Magic
email: ztmail723@gmail.com
author: 正锑
url: https://www.ztmagic.com/
resume_site: https://www.ztmagic.com/
github: https://github.com/ztmail723
baseurl: ''
description: 我们在黑暗中并肩而行
meta_description: 正锑;个人博客
motto: ZT Magic
banner: ZT Magic

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ztmail723

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

